### ISSUE TITLE
AutoSave + Prefix

### ISSUE THREAD

**Issue by nivcoo** [utarwyn/EnderContainers#130] opened 2021-03-16 14:14 UTC
Hello, can you add a command or option to save into the file, because if server crash the data is rollback.

**Comment by nivcoo** [comment] 2021-03-16 14:17
So I would like both maybe a command to save and an async automation system

**Comment by nivcoo** [comment] 2021-03-16 14:18
Then you can put the prefix in the language? I have to compile the plugin each time to change it

**Comment by utarwyn** [comment] 2021-03-16 18:23
Hello @nivcoo, thank you for these ideas!

Yes there is no command to force the data saving **because of conflicts which can happen is certain cases**. That is why I recommand the use of command `/ecp reload` which closes inventories, **saves all enderchests** and reloads the configuration in a proper order to avoid saving/loading problems.

As the plugin was designed to be as efficient as possible, the plugin saves player data only when it leaves the server. It works well 99.9% of the time! **BUT indeed** in case of a hard crash (but why does that occur?), a part of connected players data will be rollback. We can discuss a new option to be added in the configuration to force saving player data every time a chest is closed. *(which will be disabled by default, I'm not a big fan of the idea)* **What do you think of that?**

I have planned to remove entirely the prefix because it is useless, see more details here: #127

**Comment by nivcoo** [comment] 2021-03-16 20:06
Hum, so /ecp reload saves actually all enderchest ?

**Comment by nivcoo** [comment] 2021-03-16 20:08
My server does not "crash" but often it does not stop entirely without error or something that could prevent it from stopping during my automatic restart, so saving the enderchest before restarting the server would be good ^^

**Comment by utarwyn** [comment] 2021-03-17 00:05
Yes the command `/ecp reload` saves all enderchests and reloads everything. It could be a nice idea for you to execute it before the server stops if you can? But not at a given interval of time because it also closes **all inventories** of the plugin, so your players would be surprised.

**Comment by nivcoo** [comment] 2021-03-17 00:11
Yes i execute 3 commands before restart : ecp reload | save-all | stop (Because my script autorestart after that but sometimes the server stay blocked in the desactivation of one plugin (random) and idk why)

**Comment by nivcoo** [comment] 2021-03-17 00:12
Besides, I don't know if there were any postponements of that but after a /ecp reload the essentials command is no longer ovewrite, so the / enderchest command no longer works

**Comment by utarwyn** [comment] 2021-03-17 00:26
Ugh.. maybe a wrong behavior of the Essentials dependency, I will check that! So, your problem with data saving has been solved thanks to `/ecp reload` executed right before the server stop?

**Comment by utarwyn** [comment] 2021-04-02 10:55
Any news @nivcoo ?

**Comment by nivcoo** [comment] 2021-04-02 10:57
I think it works

**Comment by utarwyn** [comment] 2021-04-02 11:00
Ok thank you for the fast feedback. I have done some tests with Essentials but on my test server the `/enderchest` command is still managed by EnderContainers even after a reload, but I will do more tests I hope to find the bug.. **Which version of Essentials do you use?**

**Comment by nivcoo** [comment] 2021-04-02 11:01
The latest version of essentialsx on spigot

**Comment by nivcoo** [comment] 2021-04-02 11:02
And i havent tried today but the command is /ec which not works

**Comment by utarwyn** [comment] 2021-04-05 22:43
Hello @nivcoo! I have identified the bug and it should be fixed in my last commit :)
You can download the **latest build with the fix here**: https://ci.utarwyn.fr/job/EnderContainers/ *(current version jar)*

Sorry for the delay and the inconvenience caused by this bug..

**Comment by nivcoo** [comment] 2021-04-05 22:45
Thx i will try

**Comment by nivcoo** [comment] 2021-04-24 18:56
Hello, can you add AutoSave when we close the chest or something else in async because if my server crashes there is a huge data rollback. Thx :p

**Closed** 2024-03-25 22:52 UTC
Labels: type: enhancement
